

def MPS_permute_uneq(axis_powers):
    """
    Generate the MPS permutation array for unequal prime powers.

    Parameters
    ----------
    axis_powers : list of int
        The prime powers for each axis.

    Returns
    -------
    A : list of int
        The MPS permutation array.

    Notes
    -----
    The MPS permutation array is used to reorder the axes of a tensor in
    the MPS decomposition. The permutation array is generated by
    first finding the longest array length of the three axes and
    then adjusting the shorter arrays by adding -1s to the end.
    The resulting arrays are then concatenated to form the final
    permutation array.

    Examples
    --------
    >>> MPS_permute_uneq([2, 3, 5])
    [0, 1, 2, -1, 3, 4, 5, 6, 7]
    >>> MPS_permute_uneq([2, 3, 3])
    [0, 1, 2, -1, 3, 4, 5]
    >>> MPS_permute_uneq([2, 2, 2])
    [0, 1, -1, 2, -1, 3]
    """

    # Determine total length L
    Lx = axis_powers[0]
    Ly = axis_powers[1]
    Lz = axis_powers[2]
    L = Lx + Ly + Lz

    # Create lx, ly, lz arrays
    lx = list(range(0, Lx))
    ly = list(range(Lx, Lx + Ly))
    lz = list(range(Lx + Ly, L))

    # print("Before adjustment:")
    # print("lx:", lx)
    # print("ly:", ly)
    # print("lz:", lz)

    # Find the longest array length
    max_len = max(len(lx), len(ly), len(lz))

    # Adjust lx if it is shorter
    if len(lx) < max_len:
        diff = max_len - len(lx)
        lx = lx + [-1] * diff #Extras at the end
        # lx = [-1] * diff + lx #Extras at the beginning

    # Adjust ly if it is shorter
    if len(ly) < max_len:
        diff = max_len - len(ly)
        ly = ly + [-1] * diff #Extras at the end
        # ly = [-1] * diff + ly #Extras at the beginning

    # Adjust lz if it is shorter
    if len(lz) < max_len:
        diff = max_len - len(lz)
        lz = lz + [-1] * diff #Extras at the end
        # lz = [-1] * diff + lz #Extras at the beginning

    # print("\nAfter adjustment:")
    # print("lx:", lx)
    # print("ly:", ly)
    # print("lz:", lz)

    # Create array A
    A = []
    for i in range(max_len):
        A.extend([lx[i], ly[i], lz[i]])

    # print("\nArray A with -1 values:")
    # print(A)

    # Remove -1s from A
    A = [x for x in A if x != -1]

    # print("\nArray A without -1 values:")
    print("MPS Permutation: ",A)

    return A


def MPS_permute(Lx, Ly, Lz):

    """
    This function generates a 1D MPS permutation array given the input 1D lengths Lx, Ly, Lz.

    The permutation array is created by first generating the arrays lx, ly, lz of length Lx, Ly, Lz, respectively. The arrays are then adjusted such that they are all the same length, with the longest array length being used. The extra elements added to the shorter arrays are -1s.

    The permutation array A is then created by interleaving the elements of lx, ly, and lz. The -1s are then removed from the permutation array A.

    Parameters
    ----------
    Lx : int
        The length of the first leg of the MPS
    Ly : int
        The length of the second leg of the MPS
    Lz : int
        The length of the third leg of the MPS

    Returns
    -------
    A : list
        The 1D MPS permutation array
    """

    # Determine total length L
    L = Lx + Ly + Lz

    # Create lx, ly, lz arrays
    lx = list(range(0, Lx))
    ly = list(range(Lx, Lx + Ly))
    lz = list(range(Lx + Ly, L))

    # print("Before adjustment:")
    # print("lx:", lx)
    # print("ly:", ly)
    # print("lz:", lz)

    # Find the longest array length
    max_len = max(len(lx), len(ly), len(lz))

    # Adjust lx if it is shorter
    if len(lx) < max_len:
        diff = max_len - len(lx)
        lx = [-1] * diff + lx

    # Adjust ly if it is shorter
    if len(ly) < max_len:
        diff = max_len - len(ly)
        ly = [-1] * diff + ly

    # Adjust lz if it is shorter
    if len(lz) < max_len:
        diff = max_len - len(lz)
        lz = [-1] * diff + lz

    # print("\nAfter adjustment:")
    # print("lx:", lx)
    # print("ly:", ly)
    # print("lz:", lz)

    # Create array A
    A = []
    for i in range(max_len):
        A.extend([lx[i], ly[i], lz[i]])

    # print("\nArray A with -1 values:")
    # print(A)

    # Remove -1s from A
    A = [x for x in A if x != -1]

    # print("\nArray A without -1 values:")
    print("MPS Permutation: ",A)

    return A

